services:
  
  postgresdb:
    
    restart: unless-stopped
    env_file: .env
    image: postgres
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgresql/data
  node-application:
    build:
      context: ./  # Set project root as build context
      dockerfile: ./docker/api/Dockerfile  # Path to Dockerfile
    container_name: node-application
    depends_on:
      - postgresdb
    restart: restart
    env_file: .env
    volumes:
      - ./:/dinner_match/
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=postgresdb
      - DB_USER=${POSTGRESDB_USER}
      - DB_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - DB_NAME=${POSTGRESDB_DATABASE}
      - DB_PORT=${POSTGRESDB_DOCKER_PORT}

  # expo-app:
  #   build: ./app
  #   container_name: expo-app
  #   ports:
  #     - "19000:19000"
  #     - "19001:19001"
  #     - "19002:19002"
  #   volumes:
  #     - ./app:/app
  #     - /app/node_modules
  #   environment:
  #     - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
  #   restart: always

volumes:
  db:
    driver: local
  node-volume:
    driver: local
 